### ISSUE TITLE
Select daycare options we want to visit

### ISSUE THREAD

**Issue by meneal** [FoxysHouse/ihatework#20]
http://www.carolinaparent.com/CP/Childcare/index.php/category/Day%2BCare%2BFacilities/county/Durham/

**Comment by tchandra81** [comment]
Matt call the following places:

Children's Campus near Southpoint
Bright Horizons (one near Duke)
Duke Little School. 

Tell them your wife is a Duke physician.

**Comment by meneal** [comment]
- The Children's campus

9-11 or 3-4 tours
They accept people in June usually unless spots open.
Ratio is 1/4 teacher to student
Price is 1400 we supply everything: diapers food wipes etc. Once bbh eats
solids they feed snack and lunch every day.

I didn't select a day or time for visit since I need to know when you are
available.

Phone number is: 919-806-1900

**Comment by meneal** [comment]
I'm confused about bright horizons. There are only locations close to rtp
and one in north Durham. I don't see anything near duke. Could you tell me
which location you would like?

**Comment by meneal** [comment]
- The Little School

They seem like they will never let us or anyone in. I have no idea how anyone ever gets in. Especially for infants. Apparently they only accept nine infants and then they increase numbers
from there for each age. Twelve one year olds etc.

I said to her if we get in the list now will we have a chance when the baby
is one or two. She basically said who the hell knows.

They don't even do tours until September since apparently they block out
the entire month of august. They accept new students in August so that's
probably why. Cost is 1400 and the. Goes down every age group until 1200
for preschool.

The application process is completely online so we can just apply if you
want to.

Phone number is: (919) 354-6600

**Comment by meneal** [comment]
# Bright Horizons Duke

- Hours are 6AM - 6PM
- $35 application fee, it seems easiest to apply in person
- Openings are usually around May when people leave school but sometimes they have openings around January.
- They usually like to do tours between 9-3:30
- Cost
  - Infants (0-1): $1445/mo
  - Toddler (1-2): $1374/mo
- Phone number: 919-684-8644

Cost goes down from there.

**Comment by tchandra81** [comment]
Matt- can you set this up this week? Right now anytime on mon aug 21 will work for me.

**Comment by meneal** [comment]
Do you want me to set up for both of the two that are allowing tours now
for the same day?

**Comment by meneal** [comment]
Actually would it be possible for you to do something in September? That
way we could go to all three. Like maybe the 11th?

**Comment by tchandra81** [comment]
I'm worried about waiting too long. Can we do 1-2 next week and what's left in sept?

**Comment by meneal** [comment]
Jenny Humphries from Bright Horizons called today from 919-684-9210 to set up appointment. I missed her called her back and left a message.

**Comment by meneal** [comment]
Set up appt with Children's Campus for 9 on 8/28.

**Comment by tchandra81** [comment]
Duke Little School application done. Director to contact Tara?

**Comment by meneal** [comment]
Visit scheduled for Bright horizons.

**Comment by tchandra81** [comment]
notable Nannies placement service was recommended. 
http://www.notablenannies.com/en/Home
Message sent online on 8/17 afternoon

**Comment by tchandra81** [comment]
http://www.notablenannies.com/en/Home
