### ISSUE TITLE
Select a pediatrician

### ISSUE THREAD

**Issue by meneal** [FoxysHouse/ihatework#21]

**Comment by tchandra81** [comment]
Dr. Jenny Detert https://www.dukehealth.org/find-doctors-physicians/jenny-m-detert-md
--message left with intake person at Durham Pediatrics on 8/17 at 445 pm

**Comment by tchandra81** [comment]
Spoke to Kathy, RN at Durham Pediatrics. 
Group practice w/ 9 attending that see patients at Highgate clinic. They are all taking new patients so we should be able to get in w/ dr. Detert w/ no issues. 
Just tell the hospital that's where we are going for f/u and they will facilitate an appointment at discharge. Open M-F and some hours for sick visits and newborns Sat/Sun. 
Kathy is also the lactation consultant and some initial visits w/ her and billed under the baby to help me get breastfeeding going/trouble shoot concerns. 

I think we can close this issues and consider this resolved. By now I have had 3-5 people tell me to go to this practice and I think its best given the possible cardiology f/u stuff.

**Comment by meneal** [comment]
Sounds like that Jenny Detert person is really good. Do we need to do
anything to set up her as our peds person?
