### ISSUE TITLE
Get volt doctors to fix lan port

### ISSUE THREAD

**Issue by meneal** [FoxysHouse/ihatework#22]

**Comment by tchandra81** [comment]
should we just close this issue?

**Comment by meneal** [comment]
No I still want those guys to fix that damn thing!

**Comment by tchandra81** [comment]
ok. then what are you going to do about it? ;)

**Comment by meneal** [comment]
I might just cry and hope that does something for us.

**Comment by tchandra81** [comment]
fixed by sam
